### PR TITLE
 Github action to pull Data 100 image from Google artifact registry

### PR DESCRIPTION
**Pull request by balajialg**

### CODE REVIEW

**Comment by ryanlovett** [comment]
@balajialg You might need to use one of these action:
- https://github.com/docker/login-action?tab=readme-ov-file#google-artifact-registry-gar
- https://github.com/google-github-actions/auth

(I haven't needed to use either before.)

**Comment by balajialg** [comment]
@ryanlovett Any issues with the below stanza? I can explore those Github actions if you aren't convinced that the below stanza would do what we expect it to do.


```
    - name: Authenticate to Google Cloud
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ucb-datahub-2018

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
        echo ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} | gcloud auth activate-service-account --key-file=-
        echo $(gcloud auth print-access-token) | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev
    - name: Pull Docker image
      run: docker pull us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/data100-user-image:4497642d
```

**Comment by balajialg** [comment]
@ryanlovett I would like to test this Github action as-is once. Can I merge this PR to the repo? I will revert to your recommendations if this logic doesn't work. Let me know!

**Comment by ryanlovett** [comment]
@balajialg Please do feel free to merge to test these sorts of changes.

**Comment by balajialg** [comment]
@ryanlovett Thanks!

**Pull request merged**
