### PR TITLE
Add github actions to test whether uploaded ipynb files executes without any errors

### PR DESCRIPTION
**Pull request by balajialg**
I would like to ensure that all the uploaded ipynb files are executing without any errors. Hence, adding this github action!

Link to a reference repo -https://github.com/balajialg/ECC-Sp24/actions/runs/8855471208 where this seemed to work.

### CODE REVIEW

**Comment by shaneknapp** [comment]
two quick comments:

1) the `checkout` and `setup-python` actions are pretty old...  is there any reason you chose v2 instead of something higher?
2) this will test every notebook with every PR, even if a notebook isn't changed. it'd be preferable to test only what's changed.  i believe that this action might be useful!  https://github.com/marketplace/actions/changed-files

overall this is great and will actually help me a bit with DH-4. thanks for doing this!

**Review by shaneknapp — COMMENTED** [review]
two quick comments:

1) the `checkout` and `setup-python` actions are pretty old... is there any reason you chose v2 instead of something higher?
2) this will test every notebook with every PR, even if a notebook isn't changed. it'd be preferable to test only what's changed. i believe that this action might be useful! https://github.com/marketplace/actions/changed-files

overall this is great and will actually help me a bit with DH-4. thanks for doing this!

**Comment by ryanlovett** [comment]
Great that this feature is being added!

- Do you need to pass `--execute` to nbconvert to execute the notebooks?
- I think the action needs to be in .github/workflows/ rather than just .github/.
- I recommend putting test notebooks in a specific directory. That way the `find` command doesn't have to search the whole repo. Per @shaneknapp 's comment about only testing things that have changed, I think each deployment that has its own image should also have its own test notebooks. That way the notebooks can be tested _if_ the image changes and of course if the notebooks change.

**Comment by shaneknapp** [comment]
> Per @shaneknapp 's comment about only testing things that have changed, I think each deployment that has its own image should also have its own test notebooks. That way the notebooks can be tested _if_ the image changes and of course if the notebooks change.

yeah, we can use the github labels in the datahub repo to check for things (hub, image change, etc etc) and run them if necessary.

**Comment by shaneknapp** [comment]
>     * I think the action needs to be in .github/workflows/ rather than just .github/.

yes.  this is indeed the case!

**Comment by balajialg** [comment]
[@shaneknapp](https://github.com/shaneknapp) I don't have a rationale for using v2 and will upgrade to the latest version. I looked at a few examples while working on the Github action script and made the decision based on that.
[@ryanlovett](https://github.com/ryanlovett) [@shaneknapp](https://github.com/shaneknapp). 

~~I like the workflow to test notebooks uploaded in the test folder. I will incorporate that as part of the next PR.~~
As I started working on this, I had a few questions. While it may prove beneficial for the Datahub repository, wouldn't it be reasonable to check the latest changes in notebooks for every PR (as Shane suggested)? Should we create test notebooks for every notebook? 

I also want to check if all the notebooks in the repo are executing as some of the notebooks were uploaded many years ago. Is it a good idea to use github actions to test all notebooks? (I want to avoid the case where we launch all the notebooks in Datahub to check whether they are working fine)

**Comment by ryanlovett** [comment]
> Is it a good idea to use github actions to test all notebooks?

I think it is a good idea to use GA for this, and to only test notebooks when the images have changed or the notebooks have changed.

>  (I want to avoid the case where we launch all the notebooks in Datahub to check whether they are working fine)

To be pedantic, the notebooks would not be launched in Datahub, they'd be launched in GA.

Our images are built by CircleCI and this notebook testing would be running in GA. The GA workflow would need to pull the most recent docker image in order to test the notebooks. So imagine someone changes a dependency in the data100 image. That would kick off CircleCI to build the image and also GitHub actions at the same time. How would the latter know to wait for CircleCI to build and push the image? (and how would it get the latest image tag?) Right now, it wouldn't. Eventually, the image building will be in GA.

Maybe for now it would be sufficient for GA to try to determine what change is being made. If it is to a singleuser image or a test notebook, it would need to fetch whatever the latest singleuser image is for that deployment and run the deployment-specific notebook tests in that image. Eventually, it will be able to test the notebooks in the image it just built, but GA is not yet building images.

Alternatively, you could add this to CircleCI instead of GA. That is the most practical, but it would also feel like a missed opportunity to make more use of GA.

Or you could do both. :)

**Comment by balajialg** [comment]
> > Is it a good idea to use github actions to test all notebooks?
> 
> I think it is a good idea to use GA for this, and to only test notebooks when the images have changed or the notebooks have changed.
> 
> > (I want to avoid the case where we launch all the notebooks in Datahub to check whether they are working fine)
> 
> To be pedantic, the notebooks would not be launched in Datahub, they'd be launched in GA.
> 
> Our images are built by CircleCI and this notebook testing would be running in GA. The GA workflow would need to pull the most recent docker image in order to test the notebooks. So imagine someone changes a dependency in the data100 image. That would kick off CircleCI to build the image and also GitHub actions at the same time. How would the latter know to wait for CircleCI to build and push the image? (and how would it get the latest image tag?) Right now, it wouldn't. Eventually, the image building will be in GA.
> 
> Maybe for now it would be sufficient for GA to try to determine what change is being made. If it is to a singleuser image or a test notebook, it would need to fetch whatever the latest singleuser image is for that deployment and run the deployment-specific notebook tests in that image. Eventually, it will be able to test the notebooks in the image it just built, but GA is not yet building images.
> 
> Alternatively, you could add this to CircleCI instead of GA. That is the most practical, but it would also feel like a missed opportunity to make more use of GA.
> 
> Or you could do both. :)

@rylo Thanks a lot for the details! Are the suggestions intended for the datahub-usage-analysis repository or for the datahub repository? While I understand the steps required for the datahub repository, I'm uncertain about how to apply them to this specific repository.

FYI, I incorporated the changes recommended as part of the last 2 commits.

**Comment by ryanlovett** [comment]
@balajialg Ah, I had conflated two separate initiatives. You just want to test the usage analytics notebooks here, and not instructor notebooks. (I should have been clued in based upon this repo name -- sorry!)

In that case you can just [specify which image](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container) you want to run this in, but you'll need to pick an image tag and update it periodically as the one on the hub will change over time.

```
    container:
      image: us-central1-docker.pkg.dev/ucb-datahub-2018/user-images/dev-r-user-image:bbc5f14
```

**Comment by balajialg** [comment]
> dev-r-user-image:bbc5f14

Thanks @ryanlovett! I just pointed to the latest Data 100 image as that seems to have most of the necessary packages required by the ipynb files. I am testing the github actions in another repository to see if there are any issues with the logic.

**Comment by balajialg** [comment]
@shaneknapp @ryanlovett I tested the changes (w/o specifying data 100 image as container) in a test github repository and it seems to work fine. I would like to merge the changes to the repo and test the container image with few dummy notebooks. Let me know if you have any feedback or reservations ?

**Comment by ryanlovett** [comment]
+1 no reservations.

If you're running the tests from a datahub singleuser image, I don't think you need to install python or the other libraries from the workflow:

```
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install nbconvert nbformat
```

Those steps should only be necessary if you're using the standard GitHub Actions environment (no container) and python and the libs you need are not available. python and nbconvert are already installed in our images, and nbformat is probably too as a dependency.

**Comment by balajialg** [comment]
@ryanlovett Thanks! I removed those stanza that are not required. @shaneknapp if you have any feedback then let me know, I will address it in upcoming PRs

**Pull request merged**
