### PR TITLE
fixing dollarsign formatting

### PR DESCRIPTION
**Pull request by choldgraf**

### CODE REVIEW

**Comment by choldgraf** [comment]
I clicked "accept" but I still don't seem to have permissions on this repo

**Comment by yuvipanda** [comment]
@choldgraf unfortunately I didn't see this and pushed something else on, and now we're in conflict resolution hell I guess :'( 

I added you explicitly as a contributor here, does that help?

**Comment by choldgraf** [comment]
no worries, I was just playing around with improving the axis labeling by adding

`alt.Y('cost', axis=alt.Axis(format="$.0f", title="Cost per user"))` to the calls to plot instead of just `y='cost'`.

**Comment by choldgraf** [comment]
(it does look like I can now merge, btw)

**Pull request closed without merging**
