### PR TITLE
Quarto dashboard related changes

### PR DESCRIPTION
**Pull request by balajialg**
In this PR, I have commited the latest changes to visualize Joanna's plots as Quarto dashboards

### CODE REVIEW

**Review by shaneknapp — APPROVED** [review]

**Review by ryanlovett — COMMENTED** [review]
Perhaps the data that this references can be put in a shared volume that is only attached to specific users pods on the hub this is running on?

**Comment by balajialg** [comment]
@ryanlovett  That's a good idea. I will enable shared-read-write for the datahub-admin bcourses project site in Stat 20 Hub and add the previous three semester's data.

**Comment by shaneknapp** [comment]
> @ryanlovett That's a good idea. I will enable shared-read-write for the datahub-admin bcourses project site in Stat 20 Hub and add the previous three semester's data.

definitely a good idea...  i typically run things locally due to having 32G ram + i7 processor but dogfooding on our own service is probably for the best.  ;)

**Comment by ryanlovett** [comment]
@balajialg @shaneknapp Great! Yeah, the stat20 stanza would work, or the stat159 stanza, which mounts to ~/shared-readwrite instead of /opt. It might be best for the volume with the data to be read only actually, just so that nobody accidentally alters it.

**Comment by shaneknapp** [comment]
i'd recommend stat20 for now as stat159 is mildly wound down for the time
being.

**Comment by balajialg** [comment]
Sounds good, I also prefer to use Stat 20 stanza.

**Comment by ryanlovett** [comment]
@shaneknapp @balajialg re: stat159, it was about the config stanza itself rather than the choice of hubs.

**Comment by balajialg** [comment]
@ryanlovett I just checked both the stanzas. It makes sense to use Stat 159. I am creating a PR now. Thanks!

**Comment by shaneknapp** [comment]
👍

**Comment by balajialg** [comment]
Okay, this is done! Thanks folks.

**Pull request merged**
